name: ffigen_app_example
description: Demonstrates how to use the ffigen_app plugin.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ffigen_app:
    path: ../

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.3
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.3

flutter:

  uses-material-design: true
